[package]
name = "parrot-sync"
version = "0.0.0"
description = "TBD"
repository = "https://github.com/maniwani/parrot"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
float-ord = "0.3"
nonmax = "0"