[package]
name = "parrot-alloc"
version = "0.0.0"
description = "TBD"
repository = "https://github.com/maniwani/parrot"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
bitvec = "1"
bytesize = "1"
log = "0.4"
nonmax = "0"
num-traits = "0.2"